---
#author:  Abhijeet Janwalkar
#date:    31-05-2022
#version:   0.1
#description: Playbook to deploy a Windows VM from Template
#Changelog:
# 31-05-2022 - Initial code to deploy a Windows VM from template

- name: Create a Windows VM from template by running role
  hosts: localhost
  gather_facts: false
  vars:
    _allowed_app_sql_inputs:
      - 'yes'
      - 'no'

  vars_files:
    - "{{ input_file }}"
  
  vars_prompt:
    - name: "vCenter_user"
      prompt: "Enter Username to Deploy VM in vCenter"
      private: no
    - name: "vCenter_user_pass"
      prompt: "Enter Password for the above User"
      private: yes
    - name: "input_file"
      prompt: 'Enter location of input file to be used to deploy this VM like "\home\ansible\vmname.yml"'
      private: no
    - name: "application_sql"
      prompt: 'Will this server be used as SQL server (yes/no)'
      private: no


  pre_tasks:

  - name: Make sure application_sql is allowed (yes or no)
    fail:
      msg: >-
        The answer to  SQL server question '{{ application_sql }}' is not allowed.
        Please choose a correct option  (yes or no).
    when: not application_sql in _allowed_app_sql_inputs
    run_once: true

  tasks:
  - name: "Running Role: deployAndConfigureWindowsVm '{{ vm.Name }}'"
    include_role:
      name: deployAndConfigureWindowsVm