---
- name: Install Agent BBSA or TSA
  community.vmware.vmware_vm_shell:
    hostname: "{{ vCenter.server }}"
    validate_certs: false
    username: "{{ vCenter_user }}"
    password: "{{ vCenter_user_pass }}"
    datacenter: "{{ vCenter.dataCenter }}"
    folder: "/{{ vCenter.dataCenter }}/vm"
    vm_id: "{{ vm.Name }}"
    vm_username: "{{ local.userName }}"
    vm_password: "{{ local.userPassword }}"
    vm_shell: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe'
    vm_shell_cwd: 'C:\temp\{{ agents.bbsa.installer.folder }}'
    vm_shell_args: '-command "(.\PsExec64.exe -accepteula msiexec.exe /i {{ agents.bbsa.installer.file }} DISABLE_SMART_AGENT={{ agents.bbsa.smartAgent }} EXPORTSFILE={{ agents.bbsa.installer.exports }} USERSLOCALFILE={{ agents.bbsa.installer.userslocal }}  REBOOT=ReallySuppress /qb)"'
    wait_for_process: true
  delegate_to: localhost
  register: installBBSAAgent_output
