---
- name: Reboot VM '{{ vm.Name }}'
  community.vmware.vmware_guest:
    hostname: "{{ vCenter.server }}"
    username: '{{ vCenter_user }}'
    password: '{{ vCenter_user_pass }}'
    validate_certs: false
    datacenter: '{{ vCenter.dataCenter }}'
    state: restarted
    folder: "/{{ vCenter.dataCenter }}{{ vCenter.vmFolder }}"
    name: '{{ vm.Name }}'
    wait_for_ip_address: yes
  delegate_to: localhost

- name: wait 1 minute to reboot VM  
  ansible.builtin.pause:
    seconds: 60
  delegate_to: localhost

- name: Wait for VMware tools to become available after VM Reboot
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vCenter.server }}"
    username: "{{ vCenter_user }}"
    password: "{{ vCenter_user_pass }}"
    name: '{{ vm.Name }}'
    folder: "/{{ vCenter.dataCenter }}{{ vCenter.vmFolder }}"
    datacenter: "{{ vCenter.dataCenter }}"
    validate_certs: false
  delegate_to: localhost
  register: rebootVmAfterInstallation