---
- name: Create a new VM from Template '{{ vCenter.templateName }}' with name  '{{ vCenter.templateName }}-new' for Windows Update. 
  community.vmware.vmware_guest:
    hostname: "{{ vCenter.server }}"
    username: '{{ vCenter_user }}'
    password: '{{ vCenter_user_pass }}'
    validate_certs: false
    datacenter: '{{ vCenter.dataCenter }}'
    state: poweredon
    template: '{{ vCenter.templateName }}'
    cluster: '{{ vCenter.cluster }}' 
    datastore: '{{ vCenter.datastore }}'
    folder: "/{{ vCenter.dataCenter }}{{ vCenter.vmFolder }}"
    name: '{{ vCenter.templateName }}-new'
    hardware:
      memory_mb: '{{ vm.Memory }}'
      num_cpus: '{{ vm.Cpu }}'
    networks: "{{ vm_networks }}"
    is_template: no
    wait_for_customization: yes
    wait_for_ip_address: yes
  register: deployVmResult
  delegate_to: localhost