---
- name: Get VM UUID of newly deployed VM  '{{ vCenter.templateName }}-new' for VMware Tools update
  community.vmware.vmware_guest_facts:
    hostname: "{{ vCenter.server }}"
    username: "{{ vCenter_user }}"
    password: "{{ vCenter_user_pass }}"
    datacenter: "{{ vCenter.dataCenter }}"
    validate_certs: false
    folder: "/{{vCenter.dataCenter}}/vm"
    name: '{{ vCenter.templateName }}-new'
  delegate_to: localhost
  register: vm_facts

- name: Upgrade VMware Tools using uuid captured above for '{{ vCenter.templateName }}-new'
  community.vmware.vmware_guest_tools_upgrade:
    hostname: "{{ vCenter.server }}"
    username: "{{ vCenter_user }}"
    password: "{{ vCenter_user_pass }}"
    datacenter: "{{ vCenter.dataCenter }}"
    validate_certs: false
    uuid: "{{ vm_facts.instance.hw_product_uuid }}"
  delegate_to: localhost
  
- name: wait 1 minute to reboot VM  
  ansible.builtin.pause:
    seconds: 60
  delegate_to: localhost

- name: Wait for VMware tools to become available after VM Reboot
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vCenter.server }}"
    username: "{{ vCenter_user }}"
    password: "{{ vCenter_user_pass }}"
    name: '{{ vCenter.templateName }}-new'
    folder: "/{{ vCenter.dataCenter }}{{ vCenter.vmFolder }}"
    datacenter: "{{ vCenter.dataCenter }}"
    validate_certs: false
  delegate_to: localhost
  register: rebootVmAfterDeployment